### PR TITLE
Bugfix: locking two different files in the same directory caused an error during the last unlocking

### PR DESCRIPTION
**Pull request by cizra**

### CODE REVIEW

**Comment by clutchski** [comment]
I'm hitting this bug as well. Right now we can't hold more than one lock as well.

**Comment by erikkaplun** [comment]
Wondering why the author is refusing to merge this.

**Comment by smontanaro** [comment]
Well, let's see.
- The author lacks the time
- The author lacks experience with Github
- The author has better things to do with his time

Pick one.

S

**Comment by clutchski** [comment]
Anything I can do to help this land?

**Comment by smontanaro** [comment]
Contact me off-list. skip@pobox.com or skip@python.org.

**Comment by vikt0rs** [comment]
@smontanaro just for information - why this pull request has not been merged yet?

**Comment by smontanaro** [comment]
> @smontanaro just for information - why this pull request has not been merged yet?

I only put pylockfile on GitHub so someone would take it over. I
haven't done anything with it in a few years. If you would like it,
let me know (skip@pobox.com).

**Pull request merged**
